# text.py
# -*- coding: utf-8 -*-
#
# The python script in this file makes the various parts of a model planisphere.
#
# Copyright (C) 2014-2020 Dominic Ford <dcf21-www@dcford.org.uk>
#
# This code is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# You should have received a copy of the GNU General Public License along with
# this file; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA  02110-1301, USA

# ----------------------------------------------------------------------------

# A list of text strings, which we can render in various languages

text = {
    "en":
        {
            "title": "PLANISPHERE",
            "instructions_1": "Turn the starwheel until you find the point around its edge where today's date is marked, and line this point up with the current time. The viewing window now shows all of the constellations that are visible in the sky.",
            "instructions_2": "Go outside and face {cardinal}. Holding the planisphere up to the sky, the stars marked at the bottom of the viewing window should match up with those that you see in the sky in front of you.",
            "instructions_3": """Turn to face east or west, and rotate the planisphere so that the word "East" or "West" is at the bottom of the window. Once again, the stars at the bottom of the viewing window should match up with those that you see in the sky in front of you.""",
            "instructions_4": (
                r"A planisphere is a simple hand-held device which shows a map of which stars are visible in the night sky at any particular time. By rotating the star wheel, it shows how stars move across the sky through the night, and how different constellations are visible at different times of year.",
                "",
                r"The constellations of the night sky revolve around the celestial poles once every 23 hour and 56 minutes. The idea of representing the night sky as a flat map, which is turned to emulate the night sky's rotation, dated back to the ancient Greek astronomer Hipparchus (circa 150 BC). The fact that this rotation takes four minutes less than the length of a day means that stars rise four minutes earlier each day, or half-an-hour earlier each week. Through the year, new constellations become visible in the pre-dawn sky, and disappear into evening twilight."),
            "more_info": "For more information, see https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2020.",
            "glue_here": "GLUE HERE",
            "cut_out_instructions": (
                "Cut out this shaded area with scissors.",
                "",
                "It will become a viewing window through which to look at the star wheel behind."
            ),
            "cardinal_points": {"n": "NORTH", "s": "SOUTH", "w": "WEST", "e": "EAST"},
            "months": [
                [31, "JANUARY"],
                [28, "FEBRUARY"],
                [31, "MARCH"],
                [30, "APRIL"],
                [31, "MAY"],
                [30, "JUNE"],
                [31, "JULY"],
                [31, "AUGUST"],
                [30, "SEPTEMBER"],
                [31, "OCTOBER"],
                [30, "NOVEMBER"],
                [31, "DECEMBER"]
            ],
            "constellation_translations": {
            }
        },
    "de":
        {
            "title": "PLANISPHÄRE",
            "instructions_1": "Drehen Sie das Sternenrad bis Sie am äußeren Rand das heutige Datum finden und bringen Sie es in eine Linie mit der jetzigen Uhrzeit. Das Sichtfenster zeigt Ihnen nun alle Konstellationen, die Sie im Himmel sehen können.",
            "instructions_2": "Gehen Sie nach draußen und schauen Sie nach Norden. Halten Sie die Planisphäre hoch in den Himmel. Die Sterne am unteren Ende des Sichtfensters sollten mit den Sternen übereinstimmen, welche Sie im Himmel vor sich sehen können.",
            "instructions_3": """Drehen Sie sich nach Osten oder Westen. Dann drehen Sie die gesamte Planisphäre, so dass „Osten" oder „Westen" nach unten zeigen. Abermals stimmen die Sterne am unteren Rand des Sichtfensters mit denen am Himmel vor Ihnen überein.""",
            "instructions_4": (
                r"Eine Planisphäre ist ein einfaches Hilfsmittel das eine Karte der Sterne zeigt, welche nachts um eine ausgewählte Uhrzeit zu sehen sind. Durch Drehen des Sternenrads wird angezeigt wie die Sterne über den Himmel wandern und wie verschiedene Konstellationen über das Jahr hinweg sichtbar sind.",
                "",
                r"Die Konstellationen des Nachthimmels drehen sich um den Himmelspol alle 23 Stunden und 56 Minuten. Die Idee den Nachthimmel als flache Karte darzustellen, welche gedreht wird um die Himmelsrotation zu simulieren, geht auf den griechischen Astronomen Hipparchus zurück (ca. 150 AD). Da die Rotation vier Minuten weniger benötigt als ein Tag lang ist, hat dies zur Folge, dass die Sterne jeden Tag vier Minuten früher aufgehen, beziehungsweise eine halbe Stunde jede Woche. Während des Jahres werden dadurch neue Konstellationen am Morgenhimmel sichtbar und verschwinden in der abendlichen Dämmerung."),
            "more_info": "Für weitere Informationen, sehen Sie https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2020.",
            "glue_here": "HIER KLEBEN",
            "cut_out_instructions": (
                "Schneiden Sie diese graue Fläche mit der Schere aus.",
                "",
                "Dies wird das Sichtfenster, durch welches Sie auf das Sternenrad dahinter schauen."

            ),
            "cardinal_points": {"n": "NORDEN", "s": "SÜDEN", "w": "WESTEN", "e": "OSTEN"},
            "months": [
                [31, "JANUAR"],
                [28, "FEBRUAR"],
                [31, "MÄRZ"],
                [30, "APRIL"],
                [31, "MAI"],
                [30, "JUNI"],
                [31, "JULI"],
                [31, "AUGUST"],
                [30, "SEPTEMBER"],
                [31, "OKTOBER"],
                [30, "NOVEMBER"],
                [31, "DEZEMBER"],
            ],
            "constellation_translations": {
                "Andromeda": "Andromeda",
                "Antlia": "Luftpumpe",
                "Apus": "Paradiesvogel",
                "Aquarius": "Wassermann",
                "Aquila": "Adler",
                "Ara": "Altar",
                "Aries": "Widder",
                "Auriga": "Fuhrmann",
                "Boötes": "Bärenhüter",
                "Caelum": "Grabstichel",
                "Camelopardalis": "Giraffe",
                "Cancer": "Krebs",
                "Canes_Venatici": "Jagdhunde",
                "Canis_Major": "Großer_Hund",
                "Canis_Minor": "Kleiner_Hund",
                "Capricornus": "Steinbock",
                "Carina": "Kiel_des_Schiffs",
                "Cassiopeia": "Kassiopeia",
                "Centaurus": "Zentaur",
                "Cepheus": "Kepheus",
                "Cetus": "Walfisch",
                "Chamaeleon": "Chamäleon",
                "Circinus": "Zirkel",
                "Columba": "Taube",
                "Coma_Berenices": "Haar_der_Berenike",
                "Corona_Australis": "Südliche_Krone",
                "Corona_Borealis": "Nördliche_Krone",
                "Corvus": "Rabe",
                "Crater": "Becher",
                "Crux": "Kreuz_des_Südens",
                "Cygnus": "Schwan",
                "Delphinus": "Delphin",
                "Dorado": "Schwertfisch",
                "Draco": "Drache",
                "Equuleus": "Füllen",
                "Eridanus": "Eridanus",
                "Fornax": "Chemischer_Ofen",
                "Gemini": "Zwillinge",
                "Grus": "Kranich",
                "Hercules": "Herkules",
                "Horologium": "Pendeluhr",
                "Hydra": "Wasserschlange",
                "Hydrus": "Kleine_Wasserschlange",
                "Indus": "Indianer",
                "Lacerta": "Eidechse",
                "Leo": "Löwe",
                "Leo_Minor": "Kleiner_Löwe",
                "Lepus": "Hase",
                "Libra": "Waage",
                "Lupus": "Wolf",
                "Lynx": "Luchs",
                "Lyra": "Leier",
                "Mensa": "Tafelberg",
                "Microscopium": "Mikroskop",
                "Monoceros": "Einhorn",
                "Musca": "Fliege",
                "Norma": "Winkelmaß",
                "Octans": "Oktant",
                "Ophiuchus": "Schlangenträger",
                "Orion": "Orion",
                "Pavo": "Pfau",
                "Pegasus": "Pegasus",
                "Perseus": "Perseus",
                "Phoenix": "Phönix",
                "Pictor": "Maler",
                "Pisces": "Fische",
                "Piscis_Austrinus": "Südlicher_Fisch",
                "Puppis": "Achterdeck_des_Schiffs",
                "Pyxis": "Schiffskompass",
                "Reticulum": "Netz",
                "Sagitta": "Pfeil",
                "Sagittarius": "Schütze",
                "Scorpius": "Skorpion",
                "Sculptor": "Bildhauer",
                "Scutum": "Schild",
                "Serpens": "Schlange",
                "Sextans": "Sextant",
                "Taurus": "Stier",
                "Telescopium": "Teleskop",
                "Triangulum": "Dreieck",
                "Triangulum_Australe": "Südliches_Dreieck",
                "Tucana": "Tukan",
                "Ursa_Major": "Großer_Bär",
                "Ursa_Minor": "Kleiner_Bär",
                "Vela": "Segel_des_Schiffs",
                "Virgo": "Jungfrau",
                "Volans": "Fliegender_Fisch",
                "Vulpecula": "Fuchs",
            }
        },
    "fr":
        {
            "title": r"CHERCHE-ÉTOILES",
            "instructions_1": r"Tournez le disque de la carte du ciel jusqu'à trouver sur son pourtour le point où est inscrite la date du jour et alignez ce point avec l'heure actuelle. La fenêtre de visualisation montre maintenant toutes les constellations visibles dans le ciel.",
            "instructions_2": r"""Allez dehors et tournez-vous de manière à faire face au nord. Avec le cherche-étoiles tenu à bout de bras et le ciel en arrière-plan, les étoiles figurant au bas de la fenêtre de visualisation doivent co\"incider avec celles que vous voyez dans le ciel devant vous.""",
            "instructions_3": r"Tournez-vous vers l'est ou l'ouest, et faites pivoter le cherche-étoiles de sorte que le mot ``Est'' ou ``Ouest'' soit en bas de la fenêtre. Là encore, les étoiles dans la partie inférieure de la fenêtre de visualisation doivent correspondre à celles que vous voyez devant vous dans le ciel.",
            "instructions_4": (
                r"Un cherche-étoiles est un accessoire de poche simple fournissant une carte des étoiles visibles dans le ciel à un instant donné. Au moyen d'un disque rotatif, il montre comment les étoiles se déplacent dans le ciel pendant la nuit et la manière dont différentes constellations sont visibles selon la période de l'année.",
                "",
                r"Dans le ciel nocturne, les constellations accomplissent une révolution autour des pôles célestes toutes les 23 heures et 56 minutes. L'idée de représenter le ciel nocturne à plat sous la forme d'une carte que l'on tourne pour imiter la rotation du ciel date de l'astronome grec de l'Antiquité Hipparque (150 av. J.-C. env.). Le fait que cette rotation s'effectue en quatre minutes de moins que ce que dure une journée signifie que les étoiles se lèvent quatre minutes plus tôt chaque jour, ou une demi-heure plus tôt chaque semaine. Tout au long de l'année, de nouvelles constellations deviennent visibles dans le ciel avant l'aurore, et disparaissent dans le crépuscule en fin de journée."),
            "more_info": "Pour plus d'informations, voir https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2020.",
            "glue_here": "COLLER ICI",
            "cut_out_instructions": (
                r"Découpez cette zone grisée.",
                "",
                r"Vous pourrez voir la carte du ciel à travers cette fenêtre de visualisation."
            ),
            "cardinal_points": {"n": "NORD", "s": "SUD", "w": "OUEST", "e": "EST"},
            "months": [
                [31, "JANVIER"],
                [28, "FÉVRIER"],
                [31, "MARS"],
                [30, "AVRIL"],
                [31, "MAI"],
                [30, "JUIN"],
                [31, "JUILLET"],
                [31, "AOÛT"],
                [30, "SEPTEMBRE"],
                [31, "OCTOBRE"],
                [30, "NOVEMBRE"],
                [31, "DÉCEMBRE"]
            ],
            "constellation_translations": {
                "Andromeda": "Andromède",
                "Antlia": "Antlia",
                "Apus": "Apus",
                "Aquarius": "Verseau",
                "Aquila": "Aigle",
                "Ara": "Autel",
                "Aries": "Bélier",
                "Auriga": "Cocher",
                "Boötes": "Bouvier",
                "Caelum": "Burin",
                "Camelopardalis": "Girafe",
                "Cancer": "Cancer",
                "Canes_Venatici": "Chiens_de_chasse",
                "Canis_Major": "Grand_Chien",
                "Canis_Minor": "Petit_Chien",
                "Capricornus": "Capricorne",
                "Carina": "Carène",
                "Cassiopeia": "Cassiopée",
                "Centaurus": "Centaure",
                "Cepheus": "Céphée",
                "Cetus": "Baleine",
                "Chamaeleon": "Chamaeleon",
                "Circinus": "Circinus",
                "Columba": "Colombe",
                "Coma_Berenices": "Chevelure_de_Bérénice",
                "Corona_Australis": "Couronne_australe",
                "Corona_Borealis": "Couronne_boréale",
                "Corvus": "Corbeau",
                "Crater": "Coupe",
                "Crux": "Croix_du_Sud",
                "Cygnus": "Cygne",
                "Delphinus": "Dauphin",
                "Dorado": "Dorado",
                "Draco": "Dragon",
                "Equuleus": "Petit_Cheval",
                "Eridanus": "Éridan",
                "Fornax": "Fourneau",
                "Gemini": "Gémeaux",
                "Grus": "Grue",
                "Hercules": "Hercule",
                "Horologium": "Horloge",
                "Hydra": "Hydre",
                "Hydrus": "Hydrus",
                "Indus": "Indien",
                "Lacerta": "Lézard",
                "Leo": "Lion",
                "Leo_Minor": "Petit_Lion",
                "Lepus": "Lièvre",
                "Libra": "Balance",
                "Lupus": "Loup",
                "Lynx": "Lynx",
                "Lyra": "Lyre",
                "Mensa": "Mensa",
                "Microscopium": "Microscope",
                "Monoceros": "Licorne",
                "Musca": "Musca",
                "Norma": "Règle",
                "Octans": "Octans",
                "Ophiuchus": "Serpentaire",
                "Orion": "Orion",
                "Pavo": "Pavo",
                "Pegasus": "Pégase",
                "Perseus": "Persée",
                "Phoenix": "Phénix",
                "Pictor": "Peintre",
                "Pisces": "Poissons",
                "Piscis_Austrinus": "Poisson_austral",
                "Puppis": "Poupe",
                "Pyxis": "Boussole",
                "Reticulum": "Réticule",
                "Sagitta": "Flèche",
                "Sagittarius": "Sagittaire",
                "Scorpius": "Scorpion",
                "Sculptor": "Sculpteur",
                "Scutum": "Écu_de_Sobieski",
                "Serpens": "Serpent",
                "Sextans": "Sextant",
                "Taurus": "Taureau",
                "Telescopium": "Télescope",
                "Triangulum": "Triangle",
                "Triangulum_Australe": "Triangulum_Australe",
                "Tucana": "Toucan",
                "Ursa_Major": "Grande_Ourse",
                "Ursa_Minor": "Petite_Ourse",
                "Vela": "Voiles",
                "Virgo": "Vierge",
                "Volans": "Volans",
                "Vulpecula": "Petit_Renard"
            }
        },
    "pt":
        {
            "title": "PLANISFÉRIO",
            "instructions_1": "Gire a roda estelar até encontrar o ponto em torno da borda onde a data de hoje está marcada e alinhe esse ponto com a hora atual. A janela de visualização agora mostra todas as constelações visíveis no céu.",
            "instructions_2": "Vá lá fora e cubra {cardinal}. Segurando o planisfério em direção ao céu, as estrelas marcadas na parte inferior da janela de visualização devem coincidir com as que você vê no céu à sua frente.",
            "instructions_3": """Vire para o leste ou oeste e gire o planisfério para que a palavra "Leste" ou "Oeste" fique na parte inferior da janela. Mais uma vez, as estrelas na parte inferior da janela de visualização devem coincidir com as que você vê no céu à sua frente.""",
            "instructions_4": (
                r"Um planisfério é um dispositivo portátil simples que mostra um mapa cujas estrelas são visíveis no céu noturno a qualquer momento específico. Ao girar a roda estelar, mostra como as estrelas se movem pelo céu durante a noite e como diferentes constelações são visíveis em diferentes épocas do ano.",
                "",
                r"As constelações do céu noturno giram em torno dos pólos celestes uma vez a cada 23 horas e 56 minutos. A idéia de representar o céu noturno como um mapa plano, voltado para imitar a rotação do céu noturno, remonta ao antigo astrônomo grego Hiparco (por volta de 150 aC). O fato de essa rotação levar quatro minutos a menos que a duração de um dia significa que as estrelas aumentam quatro minutos mais cedo a cada dia, ou meia hora mais cedo a cada semana. Ao longo do ano, novas constelações se tornam visíveis no céu antes do amanhecer e desaparecem no crepúsculo da noite."),
            "more_info": "Para mais informações, veja https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2020.",
            "glue_here": "COLA AQUI",
            "cut_out_instructions": (
                "Recorte esta área sombreada com uma tesoura.",
                "",
                "Ele se tornará uma janela de visualização através da qual olhar para a roda estelar atrás."
            ),
            "cardinal_points": {"n": "NORTE", "s": "SUL", "w": "OESTE", "e": "LESTE"},
            "months": [
                [31, "JANEIRO"],
                [28, "FEVEREIRO"],
                [31, "MARÇO"],
                [30, "ABRIL"],
                [31, "MAIO"],
                [30, "JUNHO"],
                [31, "JULHO"],
                [31, "AUGOSTO"],
                [30, "SETEMBRO"],
                [31, "OUTUBRO"],
                [30, "NOVEMBRO"],
                [31, "DEZEMBRO"]
            ],
            "constellation_translations": {
                "Andromeda": "Andrômeda",
                "Antlia": "Bomba_de_Ar",
                "Apus": "Ave_do_Paraíso",
                "Aquarius": "Aquário",
                "Aquila": "Águia",
                "Ara": "Altar",
                "Aries": "Áries",
                "Auriga": "Cocheiro",
                "Boötes": "Pastor",
                "Caelum": "Buril de Escultor",
                "Camelopardalis": "Girafa",
                "Cancer": "Câncer",
                "Canes_Venatici": "Cães_de_Caça ",
                "Canis_Major": "Cão_Maior",
                "Canis_Minor": "Cão_Menor",
                "Capricornus": "Capricórnio",
                "Carina": "Quilha",
                "Cassiopeia": "Cassiopéia",
                "Centaurus": "Centauro",
                "Cepheus": "Cefeu",
                "Cetus": "Baleia",
                "Chamaeleon": "Camaleão",
                "Circinus": "Compasso",
                "Columba": "Pomba",
                "Coma_Berenices": "Cabeleira",
                "Corona_Australis": "Coroa_Austral",
                "Corona_Borealis": "Coroa_Boreal",
                "Corvus": "Corvo",
                "Crater": "Taça",
                "Crux": "Cruzeiro_do_Sul ",
                "Cygnus": "Cisne",
                "Delphinus": "Delfim",
                "Dorado": "Dourado",
                "Draco": "Dragão",
                "Equuleus": "Cabeça_de_Cavalo",
                "Eridanus": "Eridano",
                "Fornax": "Forno",
                "Gemini": "Gêmeos",
                "Grus": "Grou",
                "Hercules": "Hércules",
                "Horologium": "Relógio",
                "Hydra": "Cobra_Fêmea",
                "Hydrus": "Cobra_macho ",
                "Indus": "Índio",
                "Lacerta": "Lagarto",
                "Leo": "Leão",
                "Leo_Minor": "Leão_Menor",
                "Lepus": "Lebre",
                "Libra": "Libra",
                "Lupus": "Lobo",
                "Lynx": "Lince",
                "Lyra": "Lira",
                "Mensa": "Montanha_da_Mesa",
                "Microscopium": "Microscópio",
                "Monoceros": "Unicórnio",
                "Musca": "Mosca",
                "Norma": "Régua",
                "Octans": "Octante",
                "Ophiuchus": "Ofiúco",
                "Orion": "Órion",
                "Pavo": "Pavão",
                "Pegasus": "Pégaso",
                "Perseus": "Perseu",
                "Phoenix": "Fênix",
                "Pictor": "Cavalete_do_Pintor",
                "Pisces": "Peixes",
                "Piscis_Austrinus": "Peixe_Austral",
                "Puppis": "Popa",
                "Pyxis": "Bússola",
                "Reticulum": "Retículo",
                "Sagitta": "Flecha",
                "Sagittarius": "Sagitário",
                "Scorpius": "Escorpião",
                "Sculptor": "Escultor",
                "Scutum": "Escudo",
                "Serpens": "Serpente",
                "Sextans": "Sextante",
                "Taurus": "Touro",
                "Telescopium": "Telescópio",
                "Triangulum": "Triângulo",
                "Triangulum_Australe": "Triângulo_Austral",
                "Tucana": "Tucano",
                "Ursa_Major": "Ursa_Maior",
                "Ursa_Minor": "Ursa_Menor",
                "Vela": "Vela",
                "Virgo": "Virgem",
                "Volans": "Peixe_Voador",
                "Vulpecula": "Raposa"
            }
        }
}
