# text.py
# -*- coding: utf-8 -*-
#
# The python script in this file makes the various parts of a model planisphere.
#
# Copyright (C) 2014-2023 Dominic Ford <https://dcford.org.uk/>
#
# This code is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# You should have received a copy of the GNU General Public License along with
# this file; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA  02110-1301, USA

# ----------------------------------------------------------------------------

# A list of text strings, which we can render in various languages

text = {
    "en":
        {
            "title": "PLANISPHERE",
            "instructions_1": "Turn the star-wheel until you find the point around its edge where today's date is marked, and line this point up with the current time. The viewing window now shows all of the constellations that are visible in the sky.",
            "instructions_2": "Go outside and face {cardinal}. Holding the planisphere up to the sky, the stars marked at the bottom of the viewing window should match those that you see in the sky in front of you.",
            "instructions_3": """Turn to face east or west, and rotate the planisphere so that the word "East" or "West" is at the bottom of the window. Once again, the stars at the bottom of the viewing window should match those that you see in the sky in front of you.""",
            "instructions_4": (
                r"A planisphere is a simple hand-held device which shows a map of which stars are visible in the night sky at any particular time. By rotating the star wheel, it shows how stars move across the sky through the night, and how different constellations are visible at different times of year.",
                "",
                r"The constellations of the night sky revolve around the celestial poles once every 23 hour and 56 minutes. The idea of representing the night sky as a flat map, which is turned to emulate the night sky's rotation, dates back to the ancient Greek astronomer Hipparchus (circa 150 BC). The fact that this rotation takes four minutes less than the length of a day means that stars rise four minutes earlier each day, or half-an-hour earlier each week. Through the year, new constellations become visible in the pre-dawn sky, and disappear into evening twilight."),
            "more_info": "For more information, see https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "GLUE HERE",
            "cut_out_instructions": (
                "Cut out this shaded area with scissors.",
                "",
                "It will become a viewing window through which to look at the star wheel behind."
            ),
            "cardinal_points": {"n": "NORTH", "s": "SOUTH", "w": "WEST", "e": "EAST"},
            "months": [
                [31, "JANUARY"],
                [28, "FEBRUARY"],
                [31, "MARCH"],
                [30, "APRIL"],
                [31, "MAY"],
                [30, "JUNE"],
                [31, "JULY"],
                [31, "AUGUST"],
                [30, "SEPTEMBER"],
                [31, "OCTOBER"],
                [30, "NOVEMBER"],
                [31, "DECEMBER"]
            ],
            "constellation_translations": {
            }
        },
    "de":
        {
            "title": "PLANISPHÄRE",
            "instructions_1": "Drehen Sie das Sternenrad bis Sie am äußeren Rand das heutige Datum finden und bringen Sie es in eine Linie mit der jetzigen Uhrzeit. Das Sichtfenster zeigt Ihnen nun alle Konstellationen, die Sie im Himmel sehen können.",
            "instructions_2": "Gehen Sie nach draußen und schauen Sie nach Norden. Halten Sie die Planisphäre hoch in den Himmel. Die Sterne am unteren Ende des Sichtfensters sollten mit den Sternen übereinstimmen, welche Sie im Himmel vor sich sehen können.",
            "instructions_3": """Drehen Sie sich nach Osten oder Westen. Dann drehen Sie die gesamte Planisphäre, so dass „Osten" oder „Westen" nach unten zeigen. Abermals stimmen die Sterne am unteren Rand des Sichtfensters mit denen am Himmel vor Ihnen überein.""",
            "instructions_4": (
                r"Eine Planisphäre ist ein einfaches Hilfsmittel das eine Karte der Sterne zeigt, welche nachts um eine ausgewählte Uhrzeit zu sehen sind. Durch Drehen des Sternenrads wird angezeigt wie die Sterne über den Himmel wandern und wie verschiedene Konstellationen über das Jahr hinweg sichtbar sind.",
                "",
                r"Die Konstellationen des Nachthimmels drehen sich um den Himmelspol alle 23 Stunden und 56 Minuten. Die Idee den Nachthimmel als flache Karte darzustellen, welche gedreht wird um die Himmelsrotation zu simulieren, geht auf den griechischen Astronomen Hipparchus zurück (ca. 150 AD). Da die Rotation vier Minuten weniger benötigt als ein Tag lang ist, hat dies zur Folge, dass die Sterne jeden Tag vier Minuten früher aufgehen, beziehungsweise eine halbe Stunde jede Woche. Während des Jahres werden dadurch neue Konstellationen am Morgenhimmel sichtbar und verschwinden in der abendlichen Dämmerung."),
            "more_info": "Für weitere Informationen, sehen Sie https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "HIER KLEBEN",
            "cut_out_instructions": (
                "Schneiden Sie diese graue Fläche mit der Schere aus.",
                "",
                "Dies wird das Sichtfenster, durch welches Sie auf das Sternenrad dahinter schauen."

            ),
            "cardinal_points": {"n": "NORDEN", "s": "SÜDEN", "w": "WESTEN", "e": "OSTEN"},
            "months": [
                [31, "JANUAR"],
                [28, "FEBRUAR"],
                [31, "MÄRZ"],
                [30, "APRIL"],
                [31, "MAI"],
                [30, "JUNI"],
                [31, "JULI"],
                [31, "AUGUST"],
                [30, "SEPTEMBER"],
                [31, "OKTOBER"],
                [30, "NOVEMBER"],
                [31, "DEZEMBER"],
            ],
            "constellation_translations": {
                "Andromeda": "Andromeda",
                "Antlia": "Luftpumpe",
                "Apus": "Paradiesvogel",
                "Aquarius": "Wassermann",
                "Aquila": "Adler",
                "Ara": "Altar",
                "Aries": "Widder",
                "Auriga": "Fuhrmann",
                "Boötes": "Bärenhüter",
                "Caelum": "Grabstichel",
                "Camelopardalis": "Giraffe",
                "Cancer": "Krebs",
                "Canes_Venatici": "Jagdhunde",
                "Canis_Major": "Großer_Hund",
                "Canis_Minor": "Kleiner_Hund",
                "Capricornus": "Steinbock",
                "Carina": "Kiel_des_Schiffs",
                "Cassiopeia": "Kassiopeia",
                "Centaurus": "Zentaur",
                "Cepheus": "Kepheus",
                "Cetus": "Walfisch",
                "Chamaeleon": "Chamäleon",
                "Circinus": "Zirkel",
                "Columba": "Taube",
                "Coma_Berenices": "Haar_der_Berenike",
                "Corona_Australis": "Südliche_Krone",
                "Corona_Borealis": "Nördliche_Krone",
                "Corvus": "Rabe",
                "Crater": "Becher",
                "Crux": "Kreuz_des_Südens",
                "Cygnus": "Schwan",
                "Delphinus": "Delphin",
                "Dorado": "Schwertfisch",
                "Draco": "Drache",
                "Equuleus": "Füllen",
                "Eridanus": "Eridanus",
                "Fornax": "Chemischer_Ofen",
                "Gemini": "Zwillinge",
                "Grus": "Kranich",
                "Hercules": "Herkules",
                "Horologium": "Pendeluhr",
                "Hydra": "Wasserschlange",
                "Hydrus": "Kleine_Wasserschlange",
                "Indus": "Indianer",
                "Lacerta": "Eidechse",
                "Leo": "Löwe",
                "Leo_Minor": "Kleiner_Löwe",
                "Lepus": "Hase",
                "Libra": "Waage",
                "Lupus": "Wolf",
                "Lynx": "Luchs",
                "Lyra": "Leier",
                "Mensa": "Tafelberg",
                "Microscopium": "Mikroskop",
                "Monoceros": "Einhorn",
                "Musca": "Fliege",
                "Norma": "Winkelmaß",
                "Octans": "Oktant",
                "Ophiuchus": "Schlangenträger",
                "Orion": "Orion",
                "Pavo": "Pfau",
                "Pegasus": "Pegasus",
                "Perseus": "Perseus",
                "Phoenix": "Phönix",
                "Pictor": "Maler",
                "Pisces": "Fische",
                "Piscis_Austrinus": "Südlicher_Fisch",
                "Puppis": "Achterdeck_des_Schiffs",
                "Pyxis": "Schiffskompass",
                "Reticulum": "Netz",
                "Sagitta": "Pfeil",
                "Sagittarius": "Schütze",
                "Scorpius": "Skorpion",
                "Sculptor": "Bildhauer",
                "Scutum": "Schild",
                "Serpens": "Schlange",
                "Sextans": "Sextant",
                "Taurus": "Stier",
                "Telescopium": "Teleskop",
                "Triangulum": "Dreieck",
                "Triangulum_Australe": "Südliches_Dreieck",
                "Tucana": "Tukan",
                "Ursa_Major": "Großer_Bär",
                "Ursa_Minor": "Kleiner_Bär",
                "Vela": "Segel_des_Schiffs",
                "Virgo": "Jungfrau",
                "Volans": "Fliegender_Fisch",
                "Vulpecula": "Fuchs",
            }
        },
    "fr":
        {
            "title": r"CHERCHE-ÉTOILES",
            "instructions_1": r"Tournez le disque de la carte du ciel jusqu'à trouver sur son pourtour le point où est inscrite la date du jour et alignez ce point avec l'heure actuelle. La fenêtre de visualisation montre maintenant toutes les constellations visibles dans le ciel.",
            "instructions_2": r"""Allez dehors et tournez-vous de manière à faire face au nord. Avec le cherche-étoiles tenu à bout de bras et le ciel en arrière-plan, les étoiles figurant au bas de la fenêtre de visualisation doivent co\"incider avec celles que vous voyez dans le ciel devant vous.""",
            "instructions_3": r"Tournez-vous vers l'est ou l'ouest, et faites pivoter le cherche-étoiles de sorte que le mot ``Est'' ou ``Ouest'' soit en bas de la fenêtre. Là encore, les étoiles dans la partie inférieure de la fenêtre de visualisation doivent correspondre à celles que vous voyez devant vous dans le ciel.",
            "instructions_4": (
                r"Un cherche-étoiles est un accessoire de poche simple fournissant une carte des étoiles visibles dans le ciel à un instant donné. Au moyen d'un disque rotatif, il montre comment les étoiles se déplacent dans le ciel pendant la nuit et la manière dont différentes constellations sont visibles selon la période de l'année.",
                "",
                r"Dans le ciel nocturne, les constellations accomplissent une révolution autour des pôles célestes toutes les 23 heures et 56 minutes. L'idée de représenter le ciel nocturne à plat sous la forme d'une carte que l'on tourne pour imiter la rotation du ciel date de l'astronome grec de l'Antiquité Hipparque (150 av. J.-C. env.). Le fait que cette rotation s'effectue en quatre minutes de moins que ce que dure une journée signifie que les étoiles se lèvent quatre minutes plus tôt chaque jour, ou une demi-heure plus tôt chaque semaine. Tout au long de l'année, de nouvelles constellations deviennent visibles dans le ciel avant l'aurore, et disparaissent dans le crépuscule en fin de journée."),
            "more_info": "Pour plus d'informations, voir https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "COLLER ICI",
            "cut_out_instructions": (
                r"Découpez cette zone grisée.",
                "",
                r"Vous pourrez voir la carte du ciel à travers cette fenêtre de visualisation."
            ),
            "cardinal_points": {"n": "NORD", "s": "SUD", "w": "OUEST", "e": "EST"},
            "months": [
                [31, "JANVIER"],
                [28, "FÉVRIER"],
                [31, "MARS"],
                [30, "AVRIL"],
                [31, "MAI"],
                [30, "JUIN"],
                [31, "JUILLET"],
                [31, "AOÛT"],
                [30, "SEPTEMBRE"],
                [31, "OCTOBRE"],
                [30, "NOVEMBRE"],
                [31, "DÉCEMBRE"]
            ],
            "constellation_translations": {
                "Andromeda": "Andromède",
                "Antlia": "Antlia",
                "Apus": "Apus",
                "Aquarius": "Verseau",
                "Aquila": "Aigle",
                "Ara": "Autel",
                "Aries": "Bélier",
                "Auriga": "Cocher",
                "Boötes": "Bouvier",
                "Caelum": "Burin",
                "Camelopardalis": "Girafe",
                "Cancer": "Cancer",
                "Canes_Venatici": "Chiens_de_chasse",
                "Canis_Major": "Grand_Chien",
                "Canis_Minor": "Petit_Chien",
                "Capricornus": "Capricorne",
                "Carina": "Carène",
                "Cassiopeia": "Cassiopée",
                "Centaurus": "Centaure",
                "Cepheus": "Céphée",
                "Cetus": "Baleine",
                "Chamaeleon": "Chamaeleon",
                "Circinus": "Circinus",
                "Columba": "Colombe",
                "Coma_Berenices": "Chevelure_de_Bérénice",
                "Corona_Australis": "Couronne_australe",
                "Corona_Borealis": "Couronne_boréale",
                "Corvus": "Corbeau",
                "Crater": "Coupe",
                "Crux": "Croix_du_Sud",
                "Cygnus": "Cygne",
                "Delphinus": "Dauphin",
                "Dorado": "Dorado",
                "Draco": "Dragon",
                "Equuleus": "Petit_Cheval",
                "Eridanus": "Éridan",
                "Fornax": "Fourneau",
                "Gemini": "Gémeaux",
                "Grus": "Grue",
                "Hercules": "Hercule",
                "Horologium": "Horloge",
                "Hydra": "Hydre",
                "Hydrus": "Hydrus",
                "Indus": "Indien",
                "Lacerta": "Lézard",
                "Leo": "Lion",
                "Leo_Minor": "Petit_Lion",
                "Lepus": "Lièvre",
                "Libra": "Balance",
                "Lupus": "Loup",
                "Lynx": "Lynx",
                "Lyra": "Lyre",
                "Mensa": "Mensa",
                "Microscopium": "Microscope",
                "Monoceros": "Licorne",
                "Musca": "Musca",
                "Norma": "Règle",
                "Octans": "Octans",
                "Ophiuchus": "Serpentaire",
                "Orion": "Orion",
                "Pavo": "Pavo",
                "Pegasus": "Pégase",
                "Perseus": "Persée",
                "Phoenix": "Phénix",
                "Pictor": "Peintre",
                "Pisces": "Poissons",
                "Piscis_Austrinus": "Poisson_austral",
                "Puppis": "Poupe",
                "Pyxis": "Boussole",
                "Reticulum": "Réticule",
                "Sagitta": "Flèche",
                "Sagittarius": "Sagittaire",
                "Scorpius": "Scorpion",
                "Sculptor": "Sculpteur",
                "Scutum": "Écu_de_Sobieski",
                "Serpens": "Serpent",
                "Sextans": "Sextant",
                "Taurus": "Taureau",
                "Telescopium": "Télescope",
                "Triangulum": "Triangle",
                "Triangulum_Australe": "Triangulum_Australe",
                "Tucana": "Toucan",
                "Ursa_Major": "Grande_Ourse",
                "Ursa_Minor": "Petite_Ourse",
                "Vela": "Voiles",
                "Virgo": "Vierge",
                "Volans": "Volans",
                "Vulpecula": "Petit_Renard"
            }
        },
    "pl":
        {
            "title": "PLANISFERA",
            "instructions_1": "Obracaj kołem gwiazdowym, aż znajdziesz punkt na jego krawędzi, w którym zaznaczona jest dzisiejsza data i zrównaj ten punkt z bieżącym czasem. Okno podglądu pokazuje teraz wszystkie konstelacje widoczne na niebie.",
            "instructions_2": "Wyjdź na zewnątrz i skieruj się na północ. Trzymaj planisferę wysoko na niebie. Gwiazdy na dole okienka obserwacyjnego powinny odpowiadać gwiazdom, które widzisz na niebie przed sobą.",
            "instructions_3": """Zwróć się w stronę wschodu lub zachodu i obróć planisferę tak, aby słowo „Wschód” lub „Zachód” znalazło się na dole okna. Powtórzę raz jeszcze: gwiazdy na dole okienka obserwacyjnego powinny odpowiadać gwiazdom, które widzisz na niebie przed sobą.""",
            "instructions_4": (
                r"Planisfera to proste, ręczne urządzenie wyświetlające mapę gwiazd widocznych na nocnym niebie w określonym czasie. Obracając koło gwiazdowe, pokazuje, jak gwiazdy poruszają się po niebie w nocy i jak różne konstelacje są widoczne w różnych porach roku.",
                "",
                r"Konstelacje nocnego nieba krążą wokół biegunów niebieskich raz na 23 godziny i 56 minut. Pomysł przedstawienia nocnego nieba jako płaskiej mapy, która jest odwracana tak, aby naśladować rotację nocnego nieba, sięga starożytnego greckiego astronoma Hipparcha (około 150 roku p.n.e.). Fakt, że obrót ten trwa o cztery minuty krócej niż długość dnia, oznacza, że ​​gwiazdy wschodzą każdego dnia cztery minuty wcześniej lub pół godziny wcześniej w każdym tygodniu. W ciągu roku na niebie przed świtem widoczne są nowe konstelacje, które znikają w wieczornym zmierzchu."),
            "more_info": "Więciej informacji znajdziesz na stronie https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "TUTAJ PRZYKLEIĆ",
            "cut_out_instructions": (
                "Wytnij zacieniony obszar nożyczkami.",
                "",
                "Będzie to okno widokowe, przez które będziesz patrzeć na znajdujące się za nim koło gwiazdowe."
            ),
            "cardinal_points": {"n": "PÓŁNOC", "s": "POŁUDNIE", "w": "ZACHÓD", "e": "WSCHÓD"},
            "months": [
                [31, "STYCZEŃ"],
                [28, "LUTY"],
                [31, "MARZEC"],
                [30, "KWIECIEŃ"],
                [31, "MAJ"],
                [30, "CZERWIEC"],
                [31, "LIPIEC"],
                [31, "SIERPIEŃ"],
                [30, "WRZESIEŃ"],
                [31, "PAŹDZIERNIK"],
                [30, "LISTOPAD"],
                [31, "GRUDZIEŃ"]
            ],
            "constellation_translations": {
                "Andromeda": "Andromeda",
                "Antlia": "Pompa",
                "Apus": "Ptak_Rasjki",
                "Aquarius": "Wodnik",
                "Aquila": "Orzeł",
                "Ara": "Ołtarz",
                "Aries": "Baran",
                "Auriga": "Woźnica",
                "Boötes": "Wolarz",
                "Caelum": "Rylec",
                "Camelopardalis": "Żyrafa",
                "Cancer": "Krab",
                "Canes_Venatici": "Psy_Gończe",
                "Canis_Major": "Wielki_Pies",
                "Canis_Minor": "Mały_Pies",
                "Capricornus": "Koziorożec",
                "Carina": "Kil",
                "Cassiopeia": "Kasjopeja",
                "Centaurus": "Centaur",
                "Cepheus": "Cefeusz",
                "Cetus": "Wieloryb",
                "Chamaeleon": "Kameleon",
                "Circinus": "Cyrkiel",
                "Columba": "Gołąb",
                "Coma_Berenices": "Warkocz_Bereniki",
                "Corona_Australis": "Korona_Południowa",
                "Corona_Borealis": "Korona_Północna",
                "Corvus": "Kruk",
                "Crater": "Puchar",
                "Crux": "Krzyż_Południa",
                "Cygnus": "Łabędź",
                "Delphinus": "Dalfin",
                "Dorado": "Złota_Ryba",
                "Draco": "Smok",
                "Equuleus": "Źrebię",
                "Eridanus": "Erydan",
                "Fornax": "Piec",
                "Gemini": "Bliźnięta",
                "Grus": "Żuraw",
                "Hercules": "Herkules",
                "Horologium": "Zegar",
                "Hydra": "Hydra",
                "Hydrus": "Wąż_Wodny",
                "Indus": "Indianin",
                "Lacerta": "Jaszczurka",
                "Leo": "Lew",
                "Leo_Minor": "Mały_Lew",
                "Lepus": "Zając",
                "Libra": "Waga",
                "Lupus": "Wilk",
                "Lynx": "Ryś",
                "Lyra": "Lutnia",
                "Mensa": "Góra_Stołowa",
                "Microscopium": "Mikroskop",
                "Monoceros": "Jednorożec",
                "Musca": "Mucha",
                "Norma": "Węgielnica",
                "Octans": "Oktant",
                "Ophiuchus": "Wężownik",
                "Orion": "Orion",
                "Pavo": "Paw",
                "Pegasus": "Pegaz",
                "Perseus": "Perseusz",
                "Phoenix": "Feniks",
                "Pictor": "Malarz",
                "Pisces": "Ryby",
                "Piscis_Austrinus": "Ryba_Południowa",
                "Puppis": "Rufa",
                "Pyxis": "Kompas",
                "Reticulum": "Sieć",
                "Sagitta": "Strzała",
                "Sagittarius": "Strzelec",
                "Scorpius": "Skorpion",
                "Sculptor": "Rzeźbiarz",
                "Scutum": "Tarcza",
                "Serpens": "Wąż",
                "Sextans": "Sekstant",
                "Taurus": "Byk",
                "Telescopium": "Teleskop",
                "Triangulum": "Trójkąt",
                "Triangulum_Australe": "Trójkąt_Południowy",
                "Tucana": "Tukan",
                "Ursa_Major": "Wielka_Niedźwiedzica",
                "Ursa_Minor": "Mała_Niedźwiedzica",
                "Vela": "Żagiel",
                "Virgo": "Panna",
                "Volans": "Ryba_Latająca",
                "Vulpecula": "Lisek",
            }
        },
    "pt":
        {
            "title": "PLANISFÉRIO",
            "instructions_1": "Gire a roda estelar até encontrar o ponto em torno da borda onde a data de hoje está marcada e alinhe esse ponto com a hora atual. A janela de visualização agora mostra todas as constelações visíveis no céu.",
            "instructions_2": "Vá lá fora e cubra {cardinal}. Segurando o planisfério em direção ao céu, as estrelas marcadas na parte inferior da janela de visualização devem coincidir com as que você vê no céu à sua frente.",
            "instructions_3": """Vire para o leste ou oeste e gire o planisfério para que a palavra "Leste" ou "Oeste" fique na parte inferior da janela. Mais uma vez, as estrelas na parte inferior da janela de visualização devem coincidir com as que você vê no céu à sua frente.""",
            "instructions_4": (
                r"Um planisfério é um dispositivo portátil simples que mostra um mapa cujas estrelas são visíveis no céu noturno a qualquer momento específico. Ao girar a roda estelar, mostra como as estrelas se movem pelo céu durante a noite e como diferentes constelações são visíveis em diferentes épocas do ano.",
                "",
                r"As constelações do céu noturno giram em torno dos pólos celestes uma vez a cada 23 horas e 56 minutos. A idéia de representar o céu noturno como um mapa plano, voltado para imitar a rotação do céu noturno, remonta ao antigo astrônomo grego Hiparco (por volta de 150 aC). O fato de essa rotação levar quatro minutos a menos que a duração de um dia significa que as estrelas aumentam quatro minutos mais cedo a cada dia, ou meia hora mais cedo a cada semana. Ao longo do ano, novas constelações se tornam visíveis no céu antes do amanhecer e desaparecem no crepúsculo da noite."),
            "more_info": "Para mais informações, veja https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "COLA AQUI",
            "cut_out_instructions": (
                "Recorte esta área sombreada com uma tesoura.",
                "",
                "Ele se tornará uma janela de visualização através da qual olhar para a roda estelar atrás."
            ),
            "cardinal_points": {"n": "NORTE", "s": "SUL", "w": "OESTE", "e": "LESTE"},
            "months": [
                [31, "JANEIRO"],
                [28, "FEVEREIRO"],
                [31, "MARÇO"],
                [30, "ABRIL"],
                [31, "MAIO"],
                [30, "JUNHO"],
                [31, "JULHO"],
                [31, "AUGOSTO"],
                [30, "SETEMBRO"],
                [31, "OUTUBRO"],
                [30, "NOVEMBRO"],
                [31, "DEZEMBRO"]
            ],
            "constellation_translations": {
                "Andromeda": "Andrômeda",
                "Antlia": "Bomba_de_Ar",
                "Apus": "Ave_do_Paraíso",
                "Aquarius": "Aquário",
                "Aquila": "Águia",
                "Ara": "Altar",
                "Aries": "Áries",
                "Auriga": "Cocheiro",
                "Boötes": "Pastor",
                "Caelum": "Buril de Escultor",
                "Camelopardalis": "Girafa",
                "Cancer": "Câncer",
                "Canes_Venatici": "Cães_de_Caça ",
                "Canis_Major": "Cão_Maior",
                "Canis_Minor": "Cão_Menor",
                "Capricornus": "Capricórnio",
                "Carina": "Quilha",
                "Cassiopeia": "Cassiopéia",
                "Centaurus": "Centauro",
                "Cepheus": "Cefeu",
                "Cetus": "Baleia",
                "Chamaeleon": "Camaleão",
                "Circinus": "Compasso",
                "Columba": "Pomba",
                "Coma_Berenices": "Cabeleira",
                "Corona_Australis": "Coroa_Austral",
                "Corona_Borealis": "Coroa_Boreal",
                "Corvus": "Corvo",
                "Crater": "Taça",
                "Crux": "Cruzeiro_do_Sul ",
                "Cygnus": "Cisne",
                "Delphinus": "Delfim",
                "Dorado": "Dourado",
                "Draco": "Dragão",
                "Equuleus": "Cabeça_de_Cavalo",
                "Eridanus": "Eridano",
                "Fornax": "Forno",
                "Gemini": "Gêmeos",
                "Grus": "Grou",
                "Hercules": "Hércules",
                "Horologium": "Relógio",
                "Hydra": "Cobra_Fêmea",
                "Hydrus": "Cobra_macho ",
                "Indus": "Índio",
                "Lacerta": "Lagarto",
                "Leo": "Leão",
                "Leo_Minor": "Leão_Menor",
                "Lepus": "Lebre",
                "Libra": "Libra",
                "Lupus": "Lobo",
                "Lynx": "Lince",
                "Lyra": "Lira",
                "Mensa": "Montanha_da_Mesa",
                "Microscopium": "Microscópio",
                "Monoceros": "Unicórnio",
                "Musca": "Mosca",
                "Norma": "Régua",
                "Octans": "Octante",
                "Ophiuchus": "Ofiúco",
                "Orion": "Órion",
                "Pavo": "Pavão",
                "Pegasus": "Pégaso",
                "Perseus": "Perseu",
                "Phoenix": "Fênix",
                "Pictor": "Cavalete_do_Pintor",
                "Pisces": "Peixes",
                "Piscis_Austrinus": "Peixe_Austral",
                "Puppis": "Popa",
                "Pyxis": "Bússola",
                "Reticulum": "Retículo",
                "Sagitta": "Flecha",
                "Sagittarius": "Sagitário",
                "Scorpius": "Escorpião",
                "Sculptor": "Escultor",
                "Scutum": "Escudo",
                "Serpens": "Serpente",
                "Sextans": "Sextante",
                "Taurus": "Touro",
                "Telescopium": "Telescópio",
                "Triangulum": "Triângulo",
                "Triangulum_Australe": "Triângulo_Austral",
                "Tucana": "Tucano",
                "Ursa_Major": "Ursa_Maior",
                "Ursa_Minor": "Ursa_Menor",
                "Vela": "Vela",
                "Virgo": "Virgem",
                "Volans": "Peixe_Voador",
                "Vulpecula": "Raposa"
            }
        },
    "ukr":
        {
            "title": "ПЛАНІСФЕРА",
            "instructions_1": "Повертайте колесо з зірками доки не знайдете точку на його краю з сьогоднішньою датою та вирівняйте її з поточним часом. Тепер у оглядовому вікні відображаються всі сузір’я, видимі на небі.",
            "instructions_2": "Вийдіть на вулицю та поверніться обличчям на північ. Тримаючи планісферу над небом, зірки зображені внизу оглядового вікна повинні відповідати тим які ви бачите на небі перед собою.",
            "instructions_3": """Поверніться обличчям на схід або захід, і поверніть планісферу так, щоб слово «Схід» або «Захід» було внизу вікна. Та знов, зірки зображені внизу оглядового вікна повинні відповідати тим які ви бачите на небі перед собою.""",
            "instructions_4": (
                r"Планісфера — це простий портативний пристрій, який показує карту зірок, які видно на нічному небі в будь-який конкретний час. Повертаючи колесо з зірками, воно показує як зірки рухаються за ніч, і як видно різні сузір'я в різні пори року.",
                "",
                r"Сузір'я нічного неба обертаються навколо небесних полюсів один раз за 23 години 56 хвилин. Ідея представити нічне небо як плоску карту, яка повертається, щоб імітувати обертання нічного неба, походить від давньогрецького астронома Гіппарха (приблизно 150 р. до н. е.). Той факт, що цей оберт займає на чотири хвилини менше, ніж тривалість дня, означає, що зірки сходять на чотири хвилини раніше щодня або на півгодини раніше щотижня. Протягом року нові сузір'я стають помітними на передсвітанковому небі і зникають у вечірніх сутінках."),
            "more_info": "Більше інформації на сайті https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "ПРИКЛЕЇТИ ТУТ",
            "cut_out_instructions": (
                "Виріжте цю затінену ділянку ножицями.",
                "",
                "Це стане оглядовим вікном, через яке можна дивитися на колесо з зірками позаду."
            ),
            "cardinal_points": {"n": "ПІВНІЧ", "s": "ПІВДЕНЬ", "w": "ЗАХІД", "e": "СХІД"},
            "months": [
                [31, "СІЧЕНЬ"],
                [28, "ЛЮТИЙ"],
                [31, "БЕРЕЗЕНЬ"],
                [30, "КВІТЕНЬ"],
                [31, "ТРАВЕНЬ"],
                [30, "ЧЕРВЕНЬ"],
                [31, "ЛИПЕНЬ"],
                [31, "СЕРПЕНЬ"],
                [30, "ВЕРЕСЕНЬ"],
                [31, "ЖОВТЕНЬ"],
                [30, "ЛИСТОПАД"],
                [31, "ГРУДЕНЬ"]
            ],
            "constellation_translations": {
                "Andromeda": "Андромеда",
                "Antlia": "Насос",
                "Apus": "Райський_Птах",
                "Aquarius": "Водолій",
                "Aquila": "Орел",
                "Ara": "Жертівник",
                "Aries": "Овен",
                "Auriga": "Візничий",
                "Boötes": "Волопас",
                "Caelum": "Різець",
                "Camelopardalis": "Жирафа",
                "Cancer": "Рак",
                "Canes_Venatici": "Гончі_пси",
                "Canis_Major": "Великий_Пес",
                "Canis_Minor": "Малий_Пес",
                "Capricornus": "Козоріг",
                "Carina": "Кіль",
                "Cassiopeia": "Кассіопея",
                "Centaurus": "Центавр",
                "Cepheus": "Цефей",
                "Cetus": "Кит",
                "Chamaeleon": "Хамелеон",
                "Circinus": "Циркуль",
                "Columba": "Голуб",
                "Coma_Berenices": "Волосся",
                "Corona_Australis": "Південна_Корона",
                "Corona_Borealis": "Північна_Корона",
                "Corvus": "Ворон",
                "Crater": "Чаша",
                "Crux": "Південний_Хрест",
                "Cygnus": "Лебідь",
                "Delphinus": "Дельфін",
                "Dorado": "Золота_Риба",
                "Draco": "Дракон",
                "Equuleus": "Малий_Кінь",
                "Eridanus": "Ерідан",
                "Fornax": "Піч",
                "Gemini": "Близнюки",
                "Grus": "Журавель",
                "Hercules": "Геркулес",
                "Horologium": "Годинник",
                "Hydra": "Гідра",
                "Hydrus": "Південна_Гідра",
                "Indus": "Індієць",
                "Lacerta": "Ящірка",
                "Leo": "Лев",
                "Leo_Minor": "Малий_Лев",
                "Lepus": "Заєць",
                "Libra": "Терези",
                "Lupus": "Вовк",
                "Lynx": "Рись",
                "Lyra": "Ліра",
                "Mensa": "Столова_Гора",
                "Microscopium": "Мікроскоп",
                "Monoceros": "Одноріг",
                "Musca": "Муха",
                "Norma": "Косинець",
                "Octans": "Октант",
                "Ophiuchus": "Змієносець",
                "Orion": "Оріон",
                "Pavo": "Павич",
                "Pegasus": "Пегас",
                "Perseus": "Персей",
                "Phoenix": "Фенікс",
                "Pictor": "Живописець",
                "Pisces": "Риби",
                "Piscis_Austrinus": "Південна_Риба",
                "Puppis": "Корма",
                "Pyxis": "Компас",
                "Reticulum": "Сітка",
                "Sagitta": "Стріла",
                "Sagittarius": "Стрілець",
                "Scorpius": "Скорпіон",
                "Sculptor": "Скульптор",
                "Scutum": "Щит",
                "Serpens": "Змія",
                "Sextans": "Секстант",
                "Taurus": "Телець",
                "Telescopium": "Телескоп",
                "Triangulum": "Трикутник",
                "Triangulum_Australe": "Південний_Трикутник",
                "Tucana": "Тукан",
                "Ursa_Major": "Велика_Ведмедиця",
                "Ursa_Minor": "Мала_Ведмедиця",
                "Vela": "Паруси",
                "Virgo": "Діва",
                "Volans": "Летюча_Риба",
                "Vulpecula": "Лисичка",
            }
        },
    "es":
        {
            "title": "PLANISFERIO",
            "instructions_1": "Gira la rueda de estrellas hasta encontrar el punto del borde donde está la fecha del día, y alínealo con la hora actual. El visor ahora muestra todas las constelaciones visibles en el cielo.",
            "instructions_2": "Ve afuera y apunta al {cardinal}. Sosteniendo el planisferio hacia el cielo, las estrellas indicadas en el borde inferior del visor deberían coincidir con las que ves en el cielo frente a ti",
            "instructions_3": """Gira hacia el Este o el Oeste, y gira el planisferio hasta que la palabra "Este" u "Oeste" esté en la parte inferior del visor. Nuevamente, las estrellas en el borde inferior deberían coincidir con lo que ves en el cielo frente a ti""",
            "instructions_4": (

                r"Un planisferio es un dispositivo portátil simple que muestra un mapa de las estrellas visibles en el cielo nocturno en cualquier momento en particular. Al rotar la rueda de estrellas se muestra cómo se mueven las estrellas en el cielo durante la noche, y qué constelaciones son visibles en diferentes momentos del año.",
                "",
                r"Las constelaciones en el cielo nocturno giran alrededor de los polos celestes cada 23 horas y 56 minutos. La idea de representar el cielo nocturno como un mapa plano que se gira para emular la rotación del cielo nocturno se remonta al astrónomo Griego antiguo Hiparco de Nicea (alrededor de 150 a.C.). Como esta rotación dura menos que la longitud del día, las estrellas surgen cuatro minutos más temprano cada día, o media hora más temprano cada semana. A lo largo del año se pueden ver nuevas constelaciones en el cielo antes del amanecer, y otras desaparecen antes del atardecer."),
            "more_info": "Para más información: https://in-the-sky.org/planisphere       \u00A9 Dominic Ford 2014\u20132023.",
            "glue_here": "PEGAR AQUÍ",
            "cut_out_instructions": (
                "Corta el area sombreada con tijeras.",
                "",
                "Esto será el visor a través del que mirarás la rueda de estrellas."
            ),
            "cardinal_points": {"n": "NORTE", "s": "SUR", "w": "OESTE", "e": "ESTE"},
            "months": [
                [31, "ENERO"],
                [28, "FEBRERO"],
                [31, "MARZO"],
                [30, "ABRIL"],
                [31, "MAYO"],
                [30, "JUNIO"],
                [31, "JULIO"],
                [31, "AGOSTO"],
                [30, "SEPTIEMBRE"],
                [31, "OCTUBRE"],
                [30, "NOVIEMBRE"],
                [31, "DICIEMBRE"]
            ],
            "constellation_translations": {

            }
        }
}
